export const routeInventory = [
  { path: "/", legacyView: "homePage", react: "HomePage", access: "public", priority: "real" },
  { path: "/experiencias", legacyView: "marketplacePage", react: "CatalogPage", access: "public", priority: "real" },
  { path: "/conocenos", legacyView: "aboutPage", react: "AboutPage", access: "public", priority: "real" },
  { path: "/experiencias/:slug", legacyView: "experienceDetailPage", react: "ExperienceDetailPage", access: "public", priority: "real" },
  { path: "/vlog", legacyView: "-", react: "VlogPage", access: "public", priority: "real" },
  { path: "/destinos", legacyView: "destinationsPage", react: "DestinationsPage", access: "public", priority: "real" },
  { path: "/destinos/:slug", legacyView: "destinationsPage(slug)", react: "DestinationDetailPage", access: "public", priority: "real" },
  { path: "/reservar/:experienceId", legacyView: "bookingPage", react: "BookingSelectionPage", access: "public", priority: "real" },
  { path: "/checkout", legacyView: "checkoutPage", react: "CheckoutPage", access: "public", priority: "real" },
  { path: "/confirmacion", legacyView: "confirmationPage", react: "ConfirmationPage", access: "public", priority: "real" },
  { path: "/legal/terminos", legacyView: "legalPage(terminos)", react: "LegalPage(terminos)", access: "public", priority: "real" },
  { path: "/legal/privacidad", legacyView: "legalPage(privacidad)", react: "LegalPage(privacidad)", access: "public", priority: "real" },
  { path: "/legal/cancelacion", legacyView: "legalPage(cancelacion)", react: "LegalPage(cancelacion)", access: "public", priority: "real" },
  { path: "/legal/exencion", legacyView: "legalPage(exencion)", react: "LegalPage(exencion)", access: "public", priority: "real" },
  { path: "/admin/login", legacyView: "authPage(admin)", react: "AdminLoginPage", access: "public", priority: "real" },
  { path: "/admin/dashboard", legacyView: "adminDashboard(dashboard)", react: "AdminRoutePage(section=dashboard)", access: "admin", priority: "real" },
  { path: "/admin/reservas", legacyView: "adminDashboard(reservas)", react: "AdminRoutePage(section=reservas)", access: "admin", priority: "real" },
  { path: "/admin/calendario", legacyView: "-", react: "AdminCalendarPage", access: "admin", priority: "real" },
  { path: "/admin/pagos", legacyView: "adminDashboard(pagos)", react: "AdminRoutePage(section=pagos)", access: "admin", priority: "real" },
  { path: "/admin/experiencias", legacyView: "adminDashboard(experiencias)", react: "AdminExperiencesPage", access: "admin", priority: "real" },
  { path: "/admin/experiencias/nueva", legacyView: "adminDashboard(experiencias/nueva)", react: "AdminExperiencesPage(create)", access: "admin", priority: "real" },
  { path: "/admin/clientes", legacyView: "adminDashboard(clientes)", react: "AdminCustomersPage", access: "admin", priority: "real" },
  { path: "/admin/b2b", legacyView: "adminDashboard(b2b)", react: "DeferredMockPage", access: "admin", priority: "mock-deferred" },
  { path: "/admin/disponibilidad", legacyView: "adminDashboard(disponibilidad)", react: "AdminAvailabilityPage", access: "admin", priority: "real" },
  { path: "/admin/reportes", legacyView: "adminDashboard(reportes)", react: "AdminReportsPage", access: "admin", priority: "real" },
  { path: "/admin/configuracion", legacyView: "adminDashboard(configuracion)", react: "AdminSettingsPage", access: "admin", priority: "real" },
  { path: "/login", legacyView: "authPage(user)", react: "LoginPage", access: "customer", priority: "real" },
  { path: "/registro", legacyView: "authPage(user)", react: "RegisterPage", access: "customer", priority: "real" },
  { path: "/recuperar", legacyView: "authPage(recover)", react: "ForgotPasswordPage", access: "customer", priority: "real" },
  { path: "/usuario/nueva-clave", legacyView: "authPage(reset)", react: "ResetPasswordPage", access: "customer", priority: "real" },
  { path: "/usuario", legacyView: "userDashboard", react: "RequireCustomer>Navigate(dashboard)", access: "customer", priority: "real" },
  { path: "/usuario/dashboard", legacyView: "userDashboard(dashboard)", react: "UserDashboardPage", access: "customer", priority: "real" },
  { path: "/usuario/reservas", legacyView: "userDashboard(reservas)", react: "UserBookingsPage", access: "customer", priority: "real" },
  { path: "/usuario/calendario", legacyView: "-", react: "UserCalendarPage", access: "customer", priority: "real" },
  { path: "/usuario/favoritos", legacyView: "userDashboard(favoritos)", react: "FavoritesPage", access: "customer", priority: "real" },
  { path: "/usuario/perfil", legacyView: "userDashboard(perfil)", react: "UserProfilePage", access: "customer", priority: "real" },
  { path: "/usuario/*", legacyView: "userDashboard(*)", react: "Navigate(dashboard)", access: "customer", priority: "real" },
  { path: "/b2b", legacyView: "b2bDashboard/authPage", react: "DeferredMockPage(b2b)", access: "b2b", priority: "mock-deferred" },
  { path: "/b2b/login", legacyView: "authPage(b2b)", react: "DeferredMockPage(b2b)", access: "b2b", priority: "mock-deferred" },
  { path: "/b2b/dashboard", legacyView: "b2bDashboard(dashboard)", react: "DeferredMockPage(b2b)", access: "b2b", priority: "mock-deferred" },
  { path: "/b2b/reservas", legacyView: "b2bDashboard(reservas)", react: "DeferredMockPage(b2b)", access: "b2b", priority: "mock-deferred" },
  { path: "/b2b/comisiones", legacyView: "b2bDashboard(comisiones)", react: "DeferredMockPage(b2b)", access: "b2b", priority: "mock-deferred" },
  { path: "/b2b/clientes", legacyView: "b2bDashboard(clientes)", react: "DeferredMockPage(b2b)", access: "b2b", priority: "mock-deferred" },
  { path: "/b2b/materiales", legacyView: "b2bDashboard(materiales)", react: "DeferredMockPage(b2b)", access: "b2b", priority: "mock-deferred" },
  { path: "/b2b/*", legacyView: "b2bDashboard(*)", react: "DeferredMockPage(b2b)", access: "b2b", priority: "mock-deferred" },
];

export const realMigrationRoutes = routeInventory.filter((route) => route.priority === "real");
export const deferredMockRoutes = routeInventory.filter((route) => route.priority === "mock-deferred");
